### PR TITLE
uses v2 interface of github.com/goavro

### PR DESCRIPTION
**Pull request by karrick**
Update gogen-avro to use v2 interface of github.com/linkedin/goavro

### CODE REVIEW

**Comment by karrick** [comment]
Oops.

I forgot to push changes to goavro to make this work.

**Comment by karrick** [comment]
@alanctgardner, I typically use megacheck and golint for checking go source code.

Which checker is your CI system running?

**Comment by alanctgardner** [comment]
Sorry for the slow reply, there's no linting in CI right now, just the unit tests and integration tests. Adding megacheck and golint sounds like a good idea.

**Comment by alanctgardner** [comment]
Also thanks for taking this on!

**Pull request merged**
